print('**********STRING METHODS**********')
course = 'Python for Beginners'
print('Below examole will give the length of course')
print(len(course))
print('Below example will capitalize the course and there are more')
print(course.upper())
print(course.lower())
print('We also have method to find a letter by its index')
print(course.find('B'))
print('We also have method to replace')
print(course.replace('Beginners' , 'Professionals'))
print(course.replace('P','J'))
print('The below example contains method 'in' that return value in boolean')
print('Python' in course)
print('python' in course)
print(course.title())